const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium' });
  const ctx = await b.newContext({ viewport:{width:390,height:844}, acceptDownloads:true });
  const p = await ctx.newPage();
  const errs=[]; p.on('pageerror',e=>errs.push(e.message));
  let ok=true; const check=(n,c,i)=>{ console.log((c?'✓ ':'✗ ')+n, i!==undefined?JSON.stringify(i).slice(0,200):''); if(!c) ok=false; };
  await p.goto('http://localhost:8792/index.html'); await p.waitForTimeout(900);
  await p.evaluate(()=>{ State.s.onboarded=true; State.save(); }); await p.reload(); await p.waitForTimeout(2400);
  await p.evaluate(()=>document.querySelectorAll('.modal.modal-open').forEach(m=>UI.closeModal('#'+m.id))); await p.waitForTimeout(300);
  check('кнопка на главной', await p.evaluate(()=>!!document.querySelector('#main-remind')));
  await p.click('#main-remind'); await p.waitForTimeout(400);
  const n1 = await p.evaluate(()=>document.querySelectorAll('.remind-list li').length);
  await p.click('[data-rset="all"]'); await p.waitForTimeout(300);
  const n2 = await p.evaluate(()=>document.querySelectorAll('.remind-list li').length);
  check('«все дела» — больше событий, чем «важное»', n2 > n1, [n1, n2]);
  await p.click('[data-rbefore="10"]'); await p.waitForTimeout(200);
  const [dl] = await Promise.all([p.waitForEvent('download'), p.click('#rm-ics')]);
  const text = require('fs').readFileSync(await dl.path(), 'utf8');
  check('файл скачался', dl.suggestedFilename()==='lenivec-reminders.ics' && /BEGIN:VCALENDAR/.test(text), dl.suggestedFilename());
  check('в файле все дела и сигнал за 10 минут', (text.match(/BEGIN:VEVENT/g)||[]).length===n2 && /TRIGGER:-PT10M/.test(text));
  check('публикации — за 15 минут и ровно', /Публикация «кино»[\s\S]*?TRIGGER:-PT15M[\s\S]*?TRIGGER:PT0M/.test(text.replace(/\r\n /g,'')));
  check('настройки запомнились', await p.evaluate(()=>State.s.remind.set==='all' && State.s.remind.before===10));
  check('громкие будильники перечислены', await p.evaluate(()=>document.querySelectorAll('.remind-clock li').length===4));
  await p.evaluate(()=>{ UI.closeModal('#sheet-modal'); App.go('day'); }); await p.waitForTimeout(500);
  check('кнопка на экране «День»', await p.evaluate(()=>!!document.querySelector('#day-remind')));
  const r = await p.request.get('http://localhost:8792/reminders.ics');
  check('готовый файл лежит рядом с приложением', r.ok() && /BEGIN:VCALENDAR/.test(await r.text()));
  check('без ошибок', !errs.length, errs);
  console.log(ok ? '\n✓ напоминания в телефон работают' : '\n✗ есть проблемы');
  await b.close();
})();
