#!/usr/bin/env python3
"""Generates helper files for the offline test harness.

  build/api.luau     — Roblox classes/members/enums from the API dump (for validating property names)
  build/sources.luau — the game's Luau sources, keyed by their path in the place (from the Rojo project)

Usage: python3 tests/gen.py <API-Dump.json>
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "tests", "build")


def luau_string(text: str) -> str:
    level = 1
    while ("]" + "=" * level + "]") in text:
        level += 1
    eq = "=" * level
    return "[" + eq + "[\n" + text + "]" + eq + "]"


def parse_default(value_type, default):
    if default is None or default == "__api_dump_write_only_property__":
        return None
    cat, name = value_type["Category"], value_type["Name"]
    try:
        if cat == "Primitive":
            if name == "bool":
                return "true" if default == "true" else "false"
            if name in ("float", "double", "int", "int64"):
                if default in ("inf", "-inf", "nan"):
                    return None
                return str(float(default)) if "." in default or "e" in default else str(int(default))
            if name == "string":
                return json.dumps(default, ensure_ascii=False)
        if cat == "Enum":
            return "{ enum = %s }" % json.dumps(default)
        if cat == "DataType" and name in ("Vector3", "Vector2", "Color3"):
            nums = [float(x) for x in default.split(",")]
            if any(n != n or n in (float("inf"), float("-inf")) for n in nums):
                return None
            return "{ %s = { %s } }" % (name, ", ".join(repr(n) for n in nums))
    except (ValueError, TypeError):
        return None
    return None


def gen_api(dump_path):
    with open(dump_path, encoding="utf-8") as f:
        dump = json.load(f)
    out = ["-- generated by tests/gen.py from the Roblox API dump", "return {", "classes = {"]
    for cls in dump["Classes"]:
        tags = set(t for t in (cls.get("Tags") or []) if isinstance(t, str))
        props, events, funcs = [], [], []
        for m in cls["Members"]:
            mtags = set(t for t in (m.get("Tags") or []) if isinstance(t, str))
            sec = m.get("Security")
            if isinstance(sec, dict):
                read_sec, write_sec = sec.get("Read", "None"), sec.get("Write", "None")
            else:
                read_sec = write_sec = sec or "None"
            restricted = read_sec != "None" or "NotScriptable" in mtags
            name = m["Name"]
            if m["MemberType"] == "Property":
                vt = m["ValueType"]
                readonly = "ReadOnly" in mtags or write_sec != "None"
                default = parse_default(vt, m.get("Default"))
                fields = [
                    "t = %s" % json.dumps(vt["Category"] + ":" + vt["Name"]),
                ]
                if readonly:
                    fields.append("ro = true")
                if restricted:
                    fields.append("x = true")
                if default is not None:
                    fields.append("d = %s" % default)
                props.append("[%s] = { %s }" % (json.dumps(name), ", ".join(fields)))
            elif m["MemberType"] == "Event":
                events.append("[%s] = %s" % (json.dumps(name), "false" if restricted else "true"))
            elif m["MemberType"] == "Function":
                funcs.append("[%s] = %s" % (json.dumps(name), "false" if restricted else "true"))
            elif m["MemberType"] == "Callback":
                props.append("[%s] = { t = \"Callback\", cb = true }" % json.dumps(name))
        flags = []
        if "NotCreatable" in tags:
            flags.append("nc = true")
        if "Service" in tags:
            flags.append("svc = true")
        out.append(
            "[%s] = { s = %s, %s p = { %s }, e = { %s }, f = { %s } },"
            % (
                json.dumps(cls["Name"]),
                json.dumps(cls["Superclass"]) if cls["Superclass"] != "<<<ROOT>>>" else "nil",
                (", ".join(flags) + ",") if flags else "",
                ", ".join(props),
                ", ".join(events),
                ", ".join(funcs),
            )
        )
    out.append("},")
    out.append("enums = {")
    for enum in dump["Enums"]:
        items = ", ".join("[%s] = %d" % (json.dumps(i["Name"]), i["Value"]) for i in enum["Items"])
        out.append("[%s] = { %s }," % (json.dumps(enum["Name"]), items))
    out.append("},")
    out.append("}")
    with open(os.path.join(BUILD, "api.luau"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))


def walk_project(node, path, items):
    """Collect instances described by the Rojo project tree."""
    for key, child in node.items():
        if key.startswith("$"):
            continue
        child_path = path + [key]
        if "$path" in child:
            collect_dir(os.path.join(ROOT, child["$path"]), child_path, items)
        else:
            items.append({"path": child_path, "class": child.get("$className", "Folder")})
            walk_project(child, child_path, items)


def collect_dir(directory, path, items):
    items.append({"path": path, "class": "Folder"})
    for name in sorted(os.listdir(directory)):
        full = os.path.join(directory, name)
        if os.path.isdir(full):
            collect_dir(full, path + [name], items)
            continue
        match = re.match(r"^(.*?)(\.server|\.client)?\.luau?$", name)
        if not match:
            continue
        base, kind = match.group(1), match.group(2)
        cls = {"server": "Script", "client": "LocalScript"}.get((kind or "").lstrip("."), "ModuleScript")
        with open(full, encoding="utf-8") as f:
            source = f.read()
        items.append({"path": path + [base], "class": cls, "source": source, "file": os.path.relpath(full, ROOT)})


def gen_sources():
    with open(os.path.join(ROOT, "default.project.json"), encoding="utf-8") as f:
        project = json.load(f)
    items = []
    walk_project(project["tree"], [], items)
    out = ["-- generated by tests/gen.py", "return {"]
    for item in items:
        fields = ["path = { %s }" % ", ".join(json.dumps(p) for p in item["path"]), "class = %s" % json.dumps(item["class"])]
        if "source" in item:
            fields.append("file = %s" % json.dumps(item["file"]))
            fields.append("source = %s" % luau_string(item["source"]))
        out.append("{ %s }," % ", ".join(fields))
    out.append("}")
    with open(os.path.join(BUILD, "sources.luau"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    os.makedirs(BUILD, exist_ok=True)
    gen_api(sys.argv[1])
    gen_sources()
    print("generated", BUILD)
